# Generated by Django 5.2.1 on 2025-06-07 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_doctoravailability_day_of_week'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctoravailability',
            options={'ordering': ['day_of_week', 'start_time']},
        ),
        migrations.AlterUniqueTogether(
            name='doctoravailability',
            unique_together={('doctor', 'day_of_week', 'start_time', 'end_time')},
        ),
    ]
