# Generated by Django 4.2.21 on 2025-06-08 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_patientprofile_blood_type_patientprofile_allergies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='patient_images/'),
        ),
    ]
