# Generated by Django 5.2.1 on 2025-06-07 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_doctoravailability_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='doctoravailability',
            unique_together={('doctor', 'day_of_week')},
        ),
    ]
