# Generated by Django 5.2.1 on 2025-06-09 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_doctoravailability_unique_together'),
        ('core', '0004_patientprofile_image'),
    ]

    operations = [
    ]
