# Generated by Django 4.2.21 on 2025-06-09 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_doctoravailability_unique_together'),
        ('core', '0005_doctorreview'),
    ]

    operations = [
    ]
