# Generated by Django 4.2.21 on 2025-06-09 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_doctorprofile_image'),
        ('core', '0006_merge_20250609_1048'),
    ]

    operations = [
    ]
