# Generated by Django 4.2.21 on 2025-06-09 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_merge_20250609_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='experience',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected'), ('rescheduled', 'Rescheduled')], default='pending', max_length=15),
        ),
    ]
